// ITM_Agent/Properties/Resources.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITM_Agent.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITM_Agent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ITM Agent는 ITM 계측 장비에서 생성되는과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AboutInfo_Desc1 {
            get {
                return ResourceManager.GetString("AboutInfo_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정보를 실시간으로 모니터링 및 분류하고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AboutInfo_Desc2 {
            get {
                return ResourceManager.GetString("AboutInfo_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필요로 하는 형태로 자동 가공 · DB 적재를과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AboutInfo_Desc3 {
            get {
                return ResourceManager.GetString("AboutInfo_Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리하는 관리자 도구입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AboutInfo_Desc4 {
            get {
                return ResourceManager.GetString("AboutInfo_Desc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CAPTION_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CAPTION_INFO {
            get {
                return ResourceManager.GetString("CAPTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플러그인 변경 감지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CAPTION_PLUGIN_CHANGED {
            get {
                return ResourceManager.GetString("CAPTION_PLUGIN_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CAPTION_SAVE_COMPLETE {
            get {
                return ResourceManager.GetString("CAPTION_SAVE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CAPTION_WARNING {
            get {
                return ResourceManager.GetString("CAPTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더가 미선택되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_BASE_NOT_SELECTED {
            get {
                return ResourceManager.GetString("MSG_BASE_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 폴더를 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_FOLDER_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_FOLDER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플러그인 추가 완료.
        ///- 성공: {0}개
        ///- 중복/스킵: {1}개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_PLUGIN_ADD_RESULT {
            get {
                return ResourceManager.GetString("MSG_PLUGIN_ADD_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}개의 규칙이 삭제된 플러그인을 참조하여 초기화되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_PLUGIN_CLEARED_RULES {
            get {
                return ResourceManager.GetString("MSG_PLUGIN_CLEARED_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 {0}개의 플러그인을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_PLUGIN_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_PLUGIN_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제할 플러그인을 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_PLUGIN_SELECT_DELETE {
            get {
                return ResourceManager.GetString("MSG_PLUGIN_SELECT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규표현식을 입력해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_REGEX_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_REGEX_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행할 수 없습니다. &apos;{0}&apos; 탭의 &apos;{1}&apos; 작업에 플러그인이 선택되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_RUN_PLUGIN_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_RUN_PLUGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료형 처리 설정이 저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_SAVE_CAT_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_CAT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   증분형 처리 설정이 저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_SAVE_LIVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_LIVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 탭의 &apos;{1}&apos; 작업에 플러그인이 선택되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_SAVE_PLUGIN_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SAVE_PLUGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감시 폴더 (RegEx 목적지)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_CAT_FOLDER {
            get {
                return ResourceManager.GetString("UPLOAD_COL_CAT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 필터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_FILTER {
            get {
                return ResourceManager.GetString("UPLOAD_COL_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원본 폴더과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_LIVE_FOLDER {
            get {
                return ResourceManager.GetString("UPLOAD_COL_LIVE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 플러그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_PLUGIN {
            get {
                return ResourceManager.GetString("UPLOAD_COL_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_SELECT {
            get {
                return ResourceManager.GetString("UPLOAD_COL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_COL_TASKNAME {
            get {
                return ResourceManager.GetString("UPLOAD_COL_TASKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 분류 후 처리 (완료형)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_TAB1_HEADER {
            get {
                return ResourceManager.GetString("UPLOAD_TAB1_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원본 직접 감시 (증분형)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPLOAD_TAB2_HEADER {
            get {
                return ResourceManager.GetString("UPLOAD_TAB2_HEADER", resourceCulture);
            }
        }
    }
}
